import Head from "next/head"

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<div className="h-screen bg-slate-800 w-full p-40">
					<h1 className="text-9xl text-slate-200 uppercase">
						forget to leave
					</h1>
				</div>
			</main>
		</>
	)
}
