import Head from "next/head"
import axios from "axios"
import { type Video } from "@/types"
import VideoCard from "@/components/VideoCard"
import NoResults from "@/components/NoResults"
import { BASE_URL } from "@/utils"

interface Props {
	videos: Video[]
}

export default function Home({ videos }: Props) {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<div className="flex flex-col gap-10 video h-full">
					{videos.length ? (
						videos.map((video: Video) => (
							<VideoCard post={video} key={video._id} />
						))
					) : (
						<NoResults text="No videos found" />
					)}
				</div>
			</main>
		</>
	)
}

export const getServerSideProps = async () => {
	const { data } = await axios.get(`${BASE_URL}/api/post`)

	return {
		props: {
			videos: data,
		},
	}
}
